### ISSUE TITLE
String-Variablen+Set Makro

### ISSUE THREAD

**Issue by msaehn** [Drakulix/zwreec#113]
String Variablen können in Twee Code gesetzt und verwendet werden. Dies kompiliert zu Z-Code und wird äquivalent umgesetzt. schwierigkeit: Umsetzung der Strings in Z-Code
- [x] #66 zcode write zchars to (high) memory
- [x] #61 zcode op print_addr
- [x] #34 zcode Unicode Translation Table
- [x] strings im high-memory mit den variablen verknüpfen

**Comment by msaehn** [comment]
es wäre gut, wenn die unicode-tabelle(#34) dafür implementiert werden würde, damit in strings zumindest so einfache sonderzeichen wie äüö genutzt werden könnten

**Comment by pothos** [comment]
Plan: String-Varibalen haben als Inhalt eine Adresse und zeigen somit auf etwas im Heap oder im static-Abschnitt. Dort ist im ersten u16 die Länge vermerkt, dann kommt der String.

Bleibt nun zu klären, ob wir nur eine Art String haben oder auch ztext-Strings vs utf16-strings und vielleicht auch noch Arrays, die verschiedene Typen haben. Dann müssten wir nämlich die Typinformation mitspeichern (also boxed types), ob es sich um einen ztext-String handelt oder ein int-Array etc. Aktuell ist ein Typwechsel einer Variablen nicht erlaubt, das wäre dann sogar möglich.
Wir könnten das aber auch erstmal nicht erlauben und die Typinformation wie gehabt nur in der Symbol Table belassen.

**Comment by msaehn** [comment]
den plan finde ich gut.
wir könnten sagen mehr als 91 unicode zeichen gibt es eh nicht, dann können wir ztext-strings nutzen. auf der sicheren seite wären wir mit utf16 strings. beides zuzulassen fände ich nicht sinnvoll.

wegen den arrays. ich bin mir nicht wirklich sicher ob wir uns den schuh noch anbinden sollten. selbst wenn wir in 1.5 wochen alles schaffen sollten, gibt es an allen ecken noch etwas, was verbessert werden müsste, bzw. wo noch etwas fehlt. und falls uns wirklich langweilig sein sollte für den letzten springt, da gibt es auf alle fälle sachen die ich wichtiger finden würde als arrays bzw. als string-expressions.
wenn du aber denkst, dass wäre für dich nicht viel mehraufwand, kannst du das natürlich ebenso machen :)

**Comment by pothos** [comment]
Ich bin mir jetzt noch nicht sicher, ob die reine Unterscheidung aus der Symboltabelle raus ausreicht, um mit zwei verschiedenen Stringtypen umzugehen, daher wäre es schon leichter, nur einen zu haben. Jedoch tendiere ich eher zu utf16-Strings als den zstrings, da diese leichter zu handhaben sind, was Länge und Konkatenation angeht. Scrumgemäß würd ich also erst das machen und dann schauen, ob es erweitert wird.

**Comment by msaehn** [comment]
klingt gut. mit utf strings wären wir auf der sicheren seite. verbraucht etwas mehr speicher, aber das sollte -aktuell- nicht so das problem sein.

**Comment by felinira** [comment]
Ich bin auch dafür, erstmal UTF-16 Strings zu machen und dann zu schauen, ob es Adventures gibt, die über unsere Dateigrößenlimitierung gehen. Wenn ja lässt sich ZSCII immer noch implementieren. Grad manipulierte Strings sollten ja nicht so furchtbar lang sein.

**Comment by msaehn** [comment]
Folgendes Minimalbeispiel geht ohne Problem, deshalb merge.

```
::Start
<<set $var1 to "example 1">>
<<set $var2 to "example 2">>

<<$var1>>
<<$var2>>

<<set $var1 to "example 2">>

<<$var1>>
<<$var2>>
```

**Comment by pothos** [comment]
Naja, also $mystr + " more text" würde ich schon noch als zu unterstützendes Feature betrachten, was zu diesem Ticket gehört.

**Comment by msaehn** [comment]
ne, das zählt zu string expressions, was wir nicht gewählt haben. aber wenn du denkst das du das schaffst, auch gerne ;)

**Comment by pothos** [comment]
Ach genau, stimmt. Ist gut machbar, braucht aber noch mal eine Typinfo an dem Variablen-Struct, denke ich.
