### ISSUE TITLE
Hello World (Textausgabe)

### ISSUE THREAD

**Issue by felinira** [Drakulix/zwreec#15]
Simpler Text in der (Twee-)Start-Passage kompiliert und wird in ausführbaren Z-Code übersetzt, welcher den Text ausgibt.

Abhängigkeiten:
- [x] #13 Reguläre Definition für Twee-Lexer
- [x] #14 Kontextfreie Grammatik für Twee-Parser
- [x] #20 Erweitertes Command line parsing

**Comment by msaehn** [comment]
grobe Übersicht
![hello_world_overview](https://cloud.githubusercontent.com/assets/1397415/7547291/b4075dac-f5ea-11e4-9118-02757d688779.png)
